export const shoesData = [
  {
    id: 6,
    name: "Samba OG",
    brand: "Adidas",
    gender: "M",
    type: "Lifestyle",
    color: "Silver",
    price: 150.0,
    stock: 10,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875318/qz50na1lbrpvwmoafzwq.png",
  },
  {
    id: 7,
    name: "Adidas Harden",
    brand: "Adidas",
    gender: "F",
    type: "Basketball",
    color: "Pink",
    price: 200.0,
    stock: 20,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732876066/rgenn9ry9qjp5aj8a2fg.png",
  },
  {
    id: 8,
    name: "Elite Laceless",
    brand: "Adidas",
    gender: "M",
    type: "Football",
    color: "Red",
    price: 200.0,
    stock: 25,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732876054/vmsyudndjou52sjtsclq.png",
  },
  {
    id: 9,
    name: "Gazelle Indoor",
    brand: "Adidas",
    gender: "M",
    type: "Lifestyle",
    color: "Brown",
    price: 150.0,
    stock: 27,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732876043/mvp5guk3xrjjhixufq6o.png",
  },
  {
    id: 10,
    name: "Samba OG",
    brand: "Adidas",
    gender: "F",
    type: "Lifestyle",
    color: "Red",
    price: 160.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732876028/nrcxdx7jgu4pmtbdn9ls.png",
  },
  {
    id: 11,
    name: "Ultraboost5X",
    brand: "Adidas",
    gender: "M",
    type: "Running",
    color: "White",
    price: 300.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732876018/sckmmibxfyx8spywxnlh.png",
  },
  {
    id: 12,
    name: "Adizero",
    brand: "Adidas",
    gender: "M",
    type: "Running",
    color: "White",
    price: 250.0,
    stock: 20,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732876010/jlbtsolxvascqvkdguc2.png",
  },
  {
    id: 13,
    name: "Ultraboost5X",
    brand: "Adidas",
    gender: "F",
    type: "Running",
    color: "Yellow",
    price: 300.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732876001/zr7moibipn0m4qiwsakg.png",
  },
  {
    id: 15,
    name: "Amplimove",
    brand: "Adidas",
    gender: "M",
    type: "Training",
    color: "White",
    price: 120.0,
    stock: 25,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875983/zplkanmhdif9w8nfnn8v.png",
  },
  {
    id: 16,
    name: "Dropset",
    brand: "Adidas",
    gender: "F",
    type: "Training",
    color: "Pink",
    price: 130.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875967/e040f1oerf4xur4liyfd.png",
  },
  {
    id: 17,
    name: "JA 2",
    brand: "Nike",
    gender: "F",
    type: "Basketball",
    color: "Pink",
    price: 299.0,
    stock: 20,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875936/t6cjyvqssakjtvmcxcfc.webp",
  },
  {
    id: 18,
    name: "Kobe Protro",
    brand: "Nike",
    gender: "M",
    type: "Basketball",
    color: "Red",
    price: 299.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875945/wmtconlyecqvfywl2ast.webp",
  },
  {
    id: 19,
    name: "ZM Vapor",
    brand: "Nike",
    gender: "M",
    type: "Football",
    color: "Black",
    price: 399.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875924/wiqfk0kedixkxbxazcev.webp",
  },
  {
    id: 20,
    name: "Legend Elite",
    brand: "Nike",
    gender: "F",
    type: "Football",
    color: "Silver",
    price: 299.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875910/gsr3mca2v6aklrhxjzz3.webp",
  },
  {
    id: 21,
    name: "Book",
    brand: "Nike",
    gender: "F",
    type: "Basketball",
    color: "Pink",
    price: 299.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875896/b6vu1yyamfrb2frv7xpi.webp",
  },
  {
    id: 22,
    name: "Cortez",
    brand: "Nike",
    gender: "M",
    type: "Lifestyle",
    color: "White",
    price: 159.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875882/ipstolkn40f1drbcielg.webp",
  },
  {
    id: 23,
    name: "Air Max DN",
    brand: "Nike",
    gender: "F",
    type: "Lifestyle",
    color: "Black",
    price: 399.0,
    stock: 20,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875862/qowon6hztsvxp2p36vl6.webp",
  },
  {
    id: 24,
    name: "Air Max DN",
    brand: "Nike",
    gender: "F",
    type: "Lifestyle",
    color: "Pink",
    price: 199.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875850/x7apwqmhcy8rjr5vtvna.webp",
  },
  {
    id: 25,
    name: "Cortez",
    brand: "Nike",
    gender: "F",
    type: "Lifestyle",
    color: "White",
    price: 299.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875838/euyr0kewvbbv9eixdv9s.webp",
  },
  {
    id: 26,
    name: "Downshifter",
    brand: "Nike",
    gender: "M",
    type: "Running",
    color: "Black",
    price: 199.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875824/yy1b7ig3bdzxezqewpaz.webp",
  },
  {
    id: 27,
    name: "Pegasus",
    brand: "Nike",
    gender: "M",
    type: "Running",
    color: "White",
    price: 259.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875806/dzz0iiodld7raciezacc.webp",
  },
  {
    id: 28,
    name: "Zoom X",
    brand: "Nike",
    gender: "F",
    type: "Running",
    color: "Pink",
    price: 299.0,
    stock: 35,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875793/lzeduvrfvov7aq6yyppg.webp",
  },
  {
    id: 29,
    name: "Zoom X",
    brand: "Nike",
    gender: "F",
    type: "Running",
    color: "Pink",
    price: 399.0,
    stock: 20,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875772/pa5hukbjrh88mbscrngh.webp",
  },
  {
    id: 30,
    name: "SB Dunk Low",
    brand: "Nike",
    gender: "M",
    type: "Skateboarding",
    color: "Brown",
    price: 259.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875758/haf3fna6oe3kbmdenptr.webp",
  },
  {
    id: 31,
    name: "Zoom TR",
    brand: "Nike",
    gender: "M",
    type: "Training",
    color: "Yellow",
    price: 349.0,
    stock: 60,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875744/hjukgi1meoltweu1mnv5.webp",
  },
  {
    id: 32,
    name: "Metcon",
    brand: "Nike",
    gender: "F",
    type: "Training",
    color: "Cyan",
    price: 299.0,
    stock: 35,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875731/nigxb2wkzc6j5dl3qrfj.webp",
  },
  {
    id: 33,
    name: "Reina Easyon",
    brand: "Nike",
    gender: "F",
    type: "Training",
    color: "Green",
    price: 199.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875720/pv1qmwojvxpeev9owd4l.webp",
  },
  {
    id: 34,
    name: "Stewie",
    brand: "Puma",
    gender: "F",
    type: "Basketball",
    color: "Cyan",
    price: 349.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875692/i5fljbkdyahflypltnd5.jpg",
  },
  {
    id: 35,
    name: "Artificial GM",
    brand: "Puma",
    gender: "M",
    type: "Football",
    color: "Green",
    price: 299.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875681/iwmesg4hyy1fkfbcmo4y.jpg",
  },
  {
    id: 36,
    name: "Renaissance",
    brand: "Puma",
    gender: "M",
    type: "Lifestyle",
    color: "Brown",
    price: 399.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875670/fjljzbrmstxvknyqmhlm.jpg",
  },
  {
    id: 37,
    name: "Fenty",
    brand: "Puma",
    gender: "F",
    type: "Lifestyle",
    color: "Red",
    price: 499.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875657/vkwvjgben8mip3qowmv5.jpg",
  },
  {
    id: 38,
    name: "Deviate Nitro",
    brand: "Puma",
    gender: "M",
    type: "Running",
    color: "White",
    price: 299.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875646/nw7zwacs1qoh0btbzzc9.jpg",
  },
  {
    id: 39,
    name: "MagMax Nitro",
    brand: "Puma",
    gender: "F",
    type: "Running",
    color: "Black",
    price: 399.0,
    stock: 10,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875623/vziaimf7atcynrmd2spe.jpg",
  },
  {
    id: 40,
    name: "Magmax Nitro",
    brand: "Puma",
    gender: "F",
    type: "Running",
    color: "Green",
    price: 399.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875612/dgk0ujlx8bbzmr2zn4at.jpg",
  },
  {
    id: 41,
    name: "Palermo",
    brand: "Puma",
    gender: "M",
    type: "Skateboarding",
    color: "Yellow",
    price: 299.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875597/qq2rdrwksoi4qxkccisv.jpg",
  },
  {
    id: 42,
    name: "Palermo",
    brand: "Puma",
    gender: "F",
    type: "Skateboarding",
    color: "Silver",
    price: 399.0,
    stock: 45,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875590/wrmdpgsjkyq9jpjop8ge.jpg",
  },
  {
    id: 43,
    name: "Sin Pauk",
    brand: "SinPauk",
    gender: "M",
    type: "Lifestyle",
    color: "Black",
    price: 159.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875573/vklbda0a33mizd4y6kdz.jpg",
  },
  {
    id: 44,
    name: "Sin Pauk",
    brand: "SinPauk",
    gender: "M",
    type: "Lifestyle",
    color: "Brown",
    price: 159.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875562/phh4ctnmxux92pyaumei.jpg",
  },
  {
    id: 45,
    name: "Sin Pauk",
    brand: "SinPauk",
    gender: "M",
    type: "Lifestyle",
    color: "Red",
    price: 159.0,
    stock: 69,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875552/ptnpnjhev4rcuqpccman.jpg",
  },
  {
    id: 46,
    name: "Garza",
    brand: "Skechers",
    gender: "M",
    type: "Lifestyle",
    color: "Brown",
    price: 299.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875536/e7yrqlctionk5soq4rda.jpg",
  },
  {
    id: 47,
    name: "Work",
    brand: "Skechers",
    gender: "M",
    type: "Lifestyle",
    color: "Black",
    price: 199.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875526/cdiwmdhnizehl4inms1u.jpg",
  },
  {
    id: 48,
    name: "Glide Step",
    brand: "Skechers",
    gender: "F",
    type: "Running",
    color: "Pink",
    price: 299.0,
    stock: 60,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875514/gzzoothyyt7urxokp8iw.jpg",
  },
  {
    id: 49,
    name: "Maple Grove",
    brand: "Timberland",
    gender: "M",
    type: "Lifestyle",
    color: "Gray",
    price: 399.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875486/ciqhxsagoibraxcxcvvw.jpg",
  },
  {
    id: 50,
    name: "Maple Grove",
    brand: "Timberland",
    gender: "M",
    type: "Lifestyle",
    color: "Yellow",
    price: 399.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875473/f1tup6zqmgslfiul7luu.jpg",
  },
  {
    id: 51,
    name: "Redwood Falls",
    brand: "Timberland",
    gender: "M",
    type: "Lifestyle",
    color: "Black",
    price: 159.0,
    stock: 30,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875458/a176rrlrz6didfdlfxzt.jpg",
  },
  {
    id: 52,
    name: "Redwood Falls",
    brand: "Timberland",
    gender: "M",
    type: "Lifestyle",
    color: "Brown",
    price: 499.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875448/wldvq6vvco1btaagemtg.jpg",
  },
  {
    id: 53,
    name: "Motion Access",
    brand: "Timberland",
    gender: "M",
    type: "Running",
    color: "Orange",
    price: 399.0,
    stock: 50,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875424/iw0kcwf3cwvgejpxvj7t.jpg",
  },
  {
    id: 54,
    name: "Motion Access",
    brand: "Timberland",
    gender: "F",
    type: "Running",
    color: "Pink",
    price: 399.0,
    stock: 45,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732875405/me94yae3nbayr7h8bmsg.jpg",
  },
  {
    id: 55,
    name: "Motion Access",
    brand: "Timberland",
    gender: "F",
    type: "Running",
    color: "White",
    price: 399.0,
    stock: 40,
    image:
      "https://res.cloudinary.com/dbmms2dqc/image/upload/v1732871007/wo8vswdpseybmqjqvmyo.jpg",
  },
];
